from gui.shared.gui_items import GUI_ITEM_TYPE
from shared_utils import CONST_CONTAINER


class C11nMode(CONST_CONTAINER):
    INSTALL, SETUP = range(2)
    NAMES = {INSTALL: 'install', SETUP: 'setup'}


class C11nTabs(CONST_CONTAINER):
    STYLE, PAINT, CAMO_SHOP, CAMO_HIDDEN, CAMO_GLOBAL, CAMO_CUSTOM, EMBLEM, INSCRIPTION, EFFECT = ALL = range(9)
    AVAILABLE_REGIONS = (PAINT, CAMO_SHOP, CAMO_HIDDEN, CAMO_GLOBAL, CAMO_CUSTOM, EMBLEM, INSCRIPTION)
    VISIBLE = ALL  # legacy, maybe not all tabs will be visible, idk
    CAMO = (CAMO_SHOP, CAMO_HIDDEN, CAMO_GLOBAL, CAMO_CUSTOM)
    REGIONS = CAMO + (STYLE, EFFECT, PAINT)


ITEM_TO_TABS = {GUI_ITEM_TYPE.PAINT: (C11nTabs.PAINT,), GUI_ITEM_TYPE.CAMOUFLAGE: C11nTabs.CAMO,
                GUI_ITEM_TYPE.EMBLEM: (C11nTabs.EMBLEM,), GUI_ITEM_TYPE.INSCRIPTION: (C11nTabs.INSCRIPTION,),
                GUI_ITEM_TYPE.MODIFICATION: (C11nTabs.EFFECT,), GUI_ITEM_TYPE.STYLE: (C11nTabs.STYLE,)}


def tabToItem(tabIndex):
    return next(itemType for itemType in ITEM_TO_TABS if tabIndex in ITEM_TO_TABS[itemType])
